<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>

<div class="yay-sidenav yay-smtp-mail-detail-drawer">
  <a href="javascript:void(0)" class="closebtn">&times;</a>
  <div class="yay-smtp-layout-activity-panel-content">
	<div class="yay-smtp-activity-panel-header">
	  <h3 class="yay-smtp-activity-panel-header-title">Email log #1</h3>
	</div>
	<div class="yay-smtp-activity-panel-content panel-content">
	  <table>
		<tr>
		  <td>
			<div class="content-el datetime-el">
			  <span class="title">Time:</span>
			  <span class="content"></span>
			</div>
		  </td>
		  <td>
		  <div class="content-el from-el">
			<span class="title">From:</span>
			<span class="content"></span>
		  </div>
		  </td>
		</tr>
		<tr>
		  <td>
		  <div class="content-el to-el">
			<span class="title">To: </span>
			<span class="content"></span>
		  </div>
		  </td>
		  <td>
		  <div class="content-el subject-el">
			<span class="title">Subject: </span>
			<span class="content"></span>
		  </div>
		  </td>
		</tr>
		<tr>
		  <td>
		  <div class="content-el mailer-el">
			<span class="title">Mailer: </span>
			<span class="content"></span>
		  </div>
		  </td>
		  <td>
			<div class="content-el status-el">
			  <span class="title">Status: </span>
			  <mark><span class="content"></span></mark>
			  <span class="reason_error"></span>
			</div>
		  </td>
		</tr>
		<?php if ( 'yes' === $email_opened || 'yes' === $email_clicked_links) { ?>
		<tr>
		  <?php if ( 'yes' === $email_opened ) { ?>
		  <td>
		  	<div class="content-el tracking-opened-el">
			  <span class="title">Opened: </span>
			  <span class="content"></span>
			</div>
		  </td>
		  <?php } ?>

		  <?php if ( 'yes' === $email_clicked_links ) { ?>
		  <td>
			<div class="content-el tracking-clicked-links-el">
			  <span class="title">Clicked link: </span>
			  <span class="content"></span>
			</div>
		  </td>
		  <?php } ?>
		</tr>
		<?php } ?>
		<tr>
		  <td>
			<div class="content-el mail-source-el">
			  <span class="title">Generated by: </span>
			  <span class="content"></span>
			</div>
		  </td>
		  <td>
		  </td>
		</tr>
	  </table>
	  <div class="mail-body-el" style="padding: 10px 15px; vertical-align: baseline;">
		<div class="content-el">
		  <span class="title">Email Body</span>
		</div>
	  </div>
	  <div class="mail-body-el mail-body-content-detail" style="padding: 10px 15px; vertical-align: baseline;">

	  </div>
	</div>
  </div>
</div>